name: Deploy MkDocs GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Deploy
        run: |
          source .venv/bin/activate
          mkdocs gh-deploy --force

      - name: Register the personal access token
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      
      - name: Configure the Git credential helper
        run: gh auth setup-git
